### ISSUE TITLE
To Be Done ...

### ISSUE THREAD

**Issue by osarrouy** [AragonBlack/website#1]
- [ ] Responsiveness: it would be great to rely on https://github.com/jameslnewell/styled-components-breakpoint#readme, https://github.com/jameslnewell/styled-components-grid and https://github.com/jameslnewell/styled-components-spacing for consistency
- [ ] The logo is skewed when the screen is too small [a 13'' laptop screen already being too small] because of how SVG are displayed and render
- [ ] The nav on the right is just a mock / placeholder and does not react when clicked nor indicate the section the user is on when he scrolls.
- [ ] There is a display / latency bug on the background because of `grained.js`
- [ ] Things are not centered well 
- [ ] Colors could be adjusted a little [there is `theme.js` file in the `src/styles` dir]
- [ ] Nothing is polished [like spacing consistency, etc.]
- [ ] Probably some other stuff we will figure out in the process 😫

**Comment by deamme** [comment]
I guess we can close this for MVP, we definitely want to improve/redesign it later on with additional features such as a blog system etc.

**Comment by osarrouy** [comment]
Makes sense. Closing the issue for now.
