### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by deamme** [AragonBlack/website#6]
We might want some analytics on the website.

Aragon One is using something like https://github.com/matomo-org/matomo (for their blog), which is a better alternative to Google Analytics. Open, self-hosted, GDPR etc. An online demo for it can be seen here demo.matomo.org. Although it seems like a big setup if we want to self-host it ourselves.

Maybe there are other nice alternatives?

**Comment by osarrouy** [comment]
We should add the same analytics for the blog ... I'm not a huge fan of GA obviously but I'm feeling like we could start with GA to avoid self hosting and all the related problems. Plus GA integration is super easy by default in ghost so ...

**Comment by deamme** [comment]
Using Google analytics for now but probably going to switch to Simple Analytics.
